version: 2
updates:
  # python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - ":snake: python :snake:"
  # rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    labels:
      - "dependencies"
      - ":crab: rust :crab:"
  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
