version: 2
updates:
  # python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
